apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
data:
  mongo-user: bW9uZ291c2Vy #Diese beiden Werte sind Base64 encoded -> Das sind die tatsächlichen Zugangsdaten für die Datenbank
  mongo-password: bW9uZ29wYXNzd29yZA==