apiVersion: apps/v1 #Deployment der Web App
kind: Deployment
metadata:
  name: webapp-deployment
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
        - name: webapp
          image: nanajanashia/k8s-demo-app:v1.0
          ports:
            - containerPort: 3000 #Anwendung startet auf dem Container Port 3000, daher 3000
          env: #Wurden von der Anwendung so konfiguriert, dass die Umgebungsvariablen benötigt werden
            - name: USER_Name
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: USER_PWD
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef: #Unterschiede hier zur Secret-Verlinkung
                  name: mongo-config
                  key: mongo-url
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-service
spec: #Standard ist hierbei "ClusterIP" -> Für interne Kommunikation
  type: NodePort #NodePort sorgt für den externen Zugriff auf die Web-Anwendung
  selector:
    app: webapp
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100 #Range von 30000-32767 -> Das ist Port den externen Zugruff